// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngwyufwsznapmzcvvjrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nd3l1Zndzem5hcG16Y3Z2anJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDM3OTYsImV4cCI6MjA2NzA3OTc5Nn0.-ZiJkJEJP-LXT-B_Q00dI-qBJumP3YtgCQnuGmva_6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});